PDT24-45 | Fix Docker Hot-Reloading
pagevamp/product-traineeship-2024-shortner pull request #11
Opened 2024-12-26 09:04 UTC by noxiousghost

### Tasks

- [Fix Docker Hot-Reloading](https://outsidetech.atlassian.net/browse/PDT24-45)

### Changes

- [x] Added volume property for application container in docker-compose file to enable hot-reloading when running the application from container.
- [x] Added _auto-generated_ ormconfig.json file in gitignore

2024-12-31 01:59 UTC, arjandhakal submitted a review, later dismissed

2024-12-31 05:10 UTC, saugatmaharjan approved these changes

2024-12-31 05:20 UTC, saugatmaharjan approved these changes

2024-12-31 07:06 UTC, rrojan requested changes
Good job - there are a few potential areas of improvement but apart from that, awesome.

2024-12-31 07:06 UTC, rrojan commented on src/mailer/mailer.service.ts
> +					address: process.env.EMAIL_USER as string,
You can define this as a constant somewhere with `Address` type so it can be reused across your MailerModule

2024-12-31 12:35 UTC, noxiousghost commented on src/config/logger.config.ts
> +				new transports.File({ filename: 'logs/all.log' }),
It turns out that the existing code (without flags: 'a') works just fine. It doesn't overwrite the log files on each rebuild. so I am leaving as it is

2024-12-31 12:37 UTC, noxiousghost commented on src/mailer/mailer.service.ts
> +					address: process.env.EMAIL_USER as string,
instead, i removed sender as it will be constant across the application.

2024-12-31 12:38 UTC, noxiousghost commented on src/config/logger.config.ts
> +				new transports.File({ filename: 'logs/errors.log', level: 'error' }),
For this we'd have to install an additional package called [winston-daily-rotate-file](https://github.com/winstonjs/winston-daily-rotate-file). Do you recommend to do so?

2025-01-02 07:10 UTC, pratham-outside commented on .gitignore
> +ormconfig.json
This should not be in .gitignore

2025-01-02 09:54 UTC, rrojan approved these changes
LGTM :trophy:

2025-01-02 09:56 UTC, pratham-outside approved these changes

2025-01-02 09:59 UTC, merged