PDT24-12 | ERD for the project
pagevamp/product-traineeship-2024-shortner pull request #4
Opened 2024-12-12 06:52 UTC by noxiousghost

### Tasks
- [ERD for the project](https://outsidetech.atlassian.net/browse/PDT24-12)

### Changes
- [x] Created a schema.md and added a ERD image file inside docs/ directory of the project where the schema and ERD for the project are described.

2024-12-12 07:18 UTC, arjandhakal commented on docs/schema.md
> +- Attributes: id, shortenedUrlId, clickedAt, ipAddress, userAgent.
It would also be good to have browser, device and other attributes that can be parsed from user agent in its column.

2024-12-12 07:18 UTC, arjandhakal commented on docs/schema.md
> +- Table name: Analytics.
redirection_logs might be a more suitable name

2024-12-12 08:59 UTC, noxiousghost commented on docs/schema.md
> +- Attributes: id, shortenedUrlId, clickedAt, ipAddress, userAgent.
do you mean that we remove userAgent and have browser, device and OS columns instead?

2024-12-12 09:21 UTC, arjandhakal commented on docs/schema.md
> +- Attributes: id, shortenedUrlId, clickedAt, ipAddress, userAgent.
we can keep userAgent , but also add other columns , it would be difficult to filter based on other columns real time later on

2024-12-12 09:36 UTC, arjandhakal commented
@noxiousghost lets also make sure we only use snake_case, as that is the most compatible naming for postgres for all our columns and table names

2024-12-12 12:18 UTC, noxiousghost commented on docs/schema.md
> +- Table name: Analytics.
I have implemented them. please check my latest commit

2024-12-13 12:02 UTC, rrojan requested changes

2024-12-16 14:14 UTC, rrojan approved these changes
LGTM :trophy:

2024-12-18 05:12 UTC, arjandhakal commented on docs/schema.md
> +- Attributes: id, short_url_id, clicked_at, ip_address, user_agent, user_browser, user_device, user_platform.
for this three: let's remove the user user_browser, user_device, user_platform, and just have them as browser, device and platform

2024-12-19 04:10 UTC, arjandhakal approved these changes

2024-12-19 04:29 UTC, merged