feat(database): integrated database and its configurations for postgres
pagevamp/product-traineeship-2024-shortner pull request #5
Opened 2024-12-16 11:00 UTC by pratham-outside

### Task:
- [Set up URL shortener project database](https://outsidetech.atlassian.net/browse/PDT24-11?atlOrigin=eyJpIjoiOTI4ZjgxMjA1ODE5NGEwZGI3YzJkM2FmNGI4NGExZjIiLCJwIjoiaiJ9)
### Changes
- [x] Integrated Postgres and TypeORM to our project.
- [x] Edited example.env file.

2024-12-16 11:13 UTC, rrojan requested changes

2024-12-16 11:13 UTC, rrojan commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
Does this mean that we will be using a separate `entities/` folder to house all project entities?

2024-12-16 11:13 UTC, rrojan commented on src/database/db.module.ts
> +import { DataSource, DataSourceOptions, TypeORMError } from 'typeorm';
Let's set `semi: false` to avoid the hassle of semicolons.
This doesn't need to be done in this task, we can create a separate ticket for this.

2024-12-16 11:13 UTC, rrojan commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
Here `'__dirname'` is treated as a string not a variable :)

2024-12-16 11:13 UTC, rrojan commented on src/scripts/orm.config.ts
> +	database: process.env.POSTGRES_DB,
Let's create a separate `env.ts` file that reads and validates environment variables for us.

In the `env.ts` or similar file, we can choose to crash the app if certain env's that are critical to the functionality of our app are not provided.

2024-12-16 11:15 UTC, rrojan commented
Please also add the ticket symbol in the PR title so that context is provided to reviewers.

You can also include multiple ticket symbols so that JIRA / other pm apps pick it up and list it in their task links section.

2024-12-16 11:44 UTC, noxiousghost commented on .env.example
> +# SONAR_JDBC_PASSWORD= sonar
Lets remove unnecessary comments

2024-12-16 11:44 UTC, noxiousghost commented on .env.example
> +DB_HOST= postgresc
Lets keep uniform prefix in all env variables to avoid confusion later on; either keep DB_ or POSTGRES_ in all database related variables. IMO sticking to DB_ is much simpler to relate.

2024-12-16 11:55 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
Basically I am working on structure which consists like below:
![Screenshot from 2024-12-16 17-39-52](https://github.com/user-attachments/assets/38ef1fac-dc1f-47da-accf-d9cee986ca4e)

2024-12-16 11:57 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
SO basically yes if a feature , or anything thats needs to saved will be inside entities folder.

2024-12-16 11:58 UTC, pratham-outside commented on src/database/db.module.ts
> +import { DataSource, DataSourceOptions, TypeORMError } from 'typeorm';
semicolons are being auto generated on save , so it has not been much of a problem but sure we can do that.

2024-12-16 11:58 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
Oops! fixing it right away.

2024-12-16 11:59 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	database: process.env.POSTGRES_DB,
Sure dai will be working on that

2024-12-16 12:01 UTC, pratham-outside commented on .env.example
> +DB_HOST= postgresc
ah yes Iwas  going to tell you that , adding POSTGRES_ makes it easier to use it on docker compose file . So I used it for convenience.

2024-12-16 12:07 UTC, pratham-outside commented on src/database/db.module.ts
> +import { DataSource, DataSourceOptions, TypeORMError } from 'typeorm';
It is related to prettier config , which has already be done by Narayan and approved too.

2024-12-16 12:08 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	database: process.env.POSTGRES_DB,
Can I create a seperate ticket and work on this ?

2024-12-19 04:12 UTC, arjandhakal commented on .env.example
> +DB_HOST= postgresc
@pratham-outside I think this is still left

2024-12-19 04:14 UTC, arjandhakal commented on src/database/db.module.ts
> +					console.log('----- Connecting to DataBase ------');
This is fine for now, but we might need to have a separate logger class that does this. @pratham-outside @noxiousghost , please create a ticket to implement a common logger wrapper

2024-12-19 04:20 UTC, arjandhakal commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
Having DTO's seem an overkill as typorm handles that abstraction for us. Let's keep it simple. But, this is probably a discussion outside of this ticket's scope

2024-12-19 05:55 UTC, rrojan commented on src/main.ts
> +		console.log(`Server listening at port http://localhost:${process.env.APP_PORT}`);
You can make this a `console.info`

The reason i like doing this is because when I'm debugging I add a bunch of console.log's and I can global search and remove all of `console.log` lines at once.

When you swap this for a `console.info` this won't show up when you do that global search.

2024-12-19 05:55 UTC, rrojan approved these changes
No issues other than the minor comment I mentioned.

LGTM :trophy:

2024-12-19 08:51 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
@arjandhakal dai didn't understand what you said in a clear way. Can you refer me to any articles ? I wanted to have only a specified value through requests and nothing much than that. While refering to Nestjs documentation, this felt a nicer way . I have not been to TypeOrm articles regarding this .

2024-12-19 08:54 UTC, pratham-outside commented on .env.example
> +DB_HOST= postgresc
We agreed on keeping POSTGRES_ in env for names , I left DB_HOST as it is thinking that this host env is used by app and I wanted to make it seem like app is hosted through database.

2024-12-19 08:54 UTC, pratham-outside commented on src/database/db.module.ts
> +					console.log('----- Connecting to DataBase ------');
Sure dai !

2024-12-19 09:04 UTC, pratham-outside commented on src/scripts/orm.config.ts
> +	migrations: [join('__dirname', '/../migrations', '*.{ts,js}')],
The path configuration was mistake here regarding entities, solved that issue

2024-12-23 12:01 UTC, rrojan approved these changes

2024-12-24 06:46 UTC, arjandhakal approved these changes

2024-12-24 07:06 UTC, merged