Pdt24 17 | feat(docker): added docker and docker compose file , dockerizing both app and db
pagevamp/product-traineeship-2024-shortner pull request #7
Opened 2024-12-16 12:57 UTC by pratham-outside

### Tasks:
[Dockerize the URL shortener project](https://outsidetech.atlassian.net/browse/PDT24-17?atlOrigin=eyJpIjoiNDhhYzQ4NzJmNDMwNGQ2Njg4OWQ4YTU5NTM1MTQ0YjciLCJwIjoiaiJ9)
- [x] Created Docker Compose file.
- [x] Created Docker file.
- [x] Containerized both app and database.

2024-12-18 04:14 UTC, noxiousghost commented on Dockerfile
> +EXPOSE 3000
lets use ${APP_PORT} to expose the port from env file

2024-12-18 04:17 UTC, noxiousghost commented
Also can you add .dockerignore file to ignore things like:
- node_modules
- dist
- Dockerfile
- docker-compose.yml... and so on based on the requirement

2024-12-19 04:18 UTC, arjandhakal commented on Dockerfile
> +CMD ["yarn","run","start:dev"]
Ideally we would build and transpile and then start the server for a production ready docker image. Since, this dockerfile seems to be more for local development, let's rename it to Dockerfile.dev. Be sure to also reflect that change in the compose file

2024-12-19 04:31 UTC, saugatmaharjan commented on docker-compose.yml
> +  app-network:
let's use relevant name for network rather that generic `app-network`

2024-12-19 04:32 UTC, saugatmaharjan commented on docker-compose.yml
> +  postgresc:
why add `c` ?

2024-12-19 05:57 UTC, rrojan commented on docker-compose.yml
> +  postgresc:
Assuming that `c` stands for container this is unneeded. This isn't a container but a service, and containers will be suffixed with `serviceName-1`, `serviceName-2` anyways

2024-12-19 06:03 UTC, rrojan requested changes

2024-12-19 06:03 UTC, rrojan commented on Dockerfile
> +COPY . .
Since you have a proper `.dockerignore` I would recommend you ignore this line from Sonarqube's analysis. Otherwise it's going to keep complaining.

https://stackoverflow.com/a/30383335

```suggestion
COPY . . # NO SONAR
```

2024-12-19 06:04 UTC, pratham-outside commented on docker-compose.yml
> +  app-network:
after the docker file builds  then we will have a generic name like url-shortener-app-network . Can you give some example for some generic name what can be used here ?

2024-12-19 06:08 UTC, rrojan commented on Dockerfile
> +COPY . .
Also about the # NO SONAR property, sometimes it refuses to work so you can also try this approach @Pratham Sapkota 

Reference `sonar-project`: https://github.com/templ-project/typescript-nestjs/blob/master/sonar-project.properties
Excluding a sonar error: https://stackoverflow.com/questions/21323276/sonarqube-exclude-a-directory

2024-12-19 06:42 UTC, pratham-outside commented on docker-compose.yml
> +  postgresc:
Yes , initially I thought that this will create a container from the image but later I knew it creates a service and container name is created by docker itself joining service name , project name and numbers

2024-12-23 11:55 UTC, rrojan approved these changes
LGTM :trophy: 
Awesome work @pratham-outside

2024-12-23 11:56 UTC, merged