Pdt24 25 | Create a wrapper for environment variables
pagevamp/product-traineeship-2024-shortner pull request #9
Opened 2024-12-23 13:15 UTC by pratham-outside

### Tasks

- [Create a wrapper for environment variables](https://outsidetech.atlassian.net/browse/PDT24-25?atlOrigin=eyJpIjoiZWFhNzA3OTczNjk4NDc1MzkxNzkzOTY3NTk1NGY1N2MiLCJwIjoiaiJ9)
### Changes

- [x] Created  a new file to validate environment variables.
- [x] Use of Zod.
- [x] Validation on bootstrap of application  
- [x] Changed APP_ENV to NODE_ENV
- [X] Edited .env.example

2024-12-23 15:18 UTC, noxiousghost commented on sonar-project.properties
> +sonar.exclusions= **/*
I think this ignores all the files in the project. Lets setup this file as: 
```
sonar.projectKey=product-traineeship-2024-shortner
sonar.projectName=product-traineeship-2024-shortner
sonar.projectVersion=0.0.1
sonar.sources=src
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/Dockerfile
```
Here, we've setup some of the important settings. You can refer to [this example](https://www.devopsschool.com/blog/example-of-sonar-project-properties-file/) for understanding what these settings do. Also the sonar.projectKey and projectName values should be same as the values in our project SonarCloud. These values should be provided to us by the one who setup sonarqube in this project. Ideally they are same as the Github repo name.

2024-12-23 15:27 UTC, pratham-outside commented on sonar-project.properties
> +sonar.exclusions= **/*
Rojan dai has already disabled checking of docker file from sonar dashboard, i think now its ok to delete it , in main branch we can just add adjustments for docker file or we can do as you said.

2024-12-23 15:31 UTC, pratham-outside commented on src/config/env.config.ts
> +		throw new Error(`---${value.error.issues[0].path} :: ${value.error.issues[0].message.toUpperCase()}---`);
Its just for clarity to see error messages , it seperates from rest of the words and set our attention directly to error.

2024-12-23 15:33 UTC, pratham-outside commented on src/config/env.config.ts
> +	APP_PORT: +(process.env.APP_PORT || 3000),
when providing + infront of a string like above it must be a number or else typescript gives error saying "it is probably undefined". 
`'process.env.POSTGRES_PORT' is possibly 'undefined'.`  , so to remove error i gave a default value which is a number saying that it wont give undefined value. We must probably refer to the package envalid as we discussed earlier.

2024-12-24 06:49 UTC, arjandhakal commented on src/config/env.config.ts
> +	APP_PORT: +(process.env.APP_PORT || 3000),
I think its okay to have default values for port

2024-12-24 08:54 UTC, arjandhakal commented on src/main.ts
> +	const port = envVariables.APP_PORT ?? 3000;
No need for default value if we're already defining it in envVariables

2024-12-27 07:14 UTC, rrojan requested changes

2024-12-27 07:14 UTC, rrojan commented on src/app.module.ts
>  import { ConfigModule } from '@nestjs/config';
Please prefer import aliases `"@/*"` rather than relative imports.

It will help a lot for code organization.

2024-12-27 07:14 UTC, rrojan commented on src/config/env.config.ts
> +export const validate = (): object => {
Use return type `z.infer(typeof validationSchema)` instead of `object`

2024-12-27 07:14 UTC, rrojan commented on src/config/env.config.ts
> +export const envVariables = {
```suggestion
export const env = {
```

2024-12-27 07:14 UTC, rrojan commented on src/scripts/orm.config.ts
> +	port: +(envVariables.POSTGRES_PORT ?? '5432'),
After we return `z.infer<typeof validationSchema>` env.POSTGRES_PORT will not be falsey.

2024-12-27 07:14 UTC, rrojan commented on src/scripts/orm.config.ts
>  	synchronize: false, // Should be false in production to use migrations
```suggestion
	database: envVariables.POSTGRES_DB,
	synchronize: ${env.NODE_ENV === APP_ENVIRONVENT.PRODUCTION}
```

2024-12-29 00:41 UTC, rrojan commented on src/scripts/orm.config.ts
>  	synchronize: false, // Should be false in production to use migrations
Typo:
env.NODE_ENV !== APP_ENVIRONVENT.PRODUCTION

2024-12-30 11:45 UTC, rrojan approved these changes
Small nitpick. Apart from this LGTM :trophy:

2024-12-30 11:45 UTC, rrojan commented on src/scripts/orm.config.ts
> +	synchronize: env.NODE_ENV === APP_ENVIRONVENT.PRODUCTION ? false : true, // Should be false in production to use migrations
```suggestion
	synchronize: env.NODE_ENV === APP_ENVIRONVENT.DEVELOPMENT,
```

2024-12-31 01:58 UTC, arjandhakal submitted a review, later dismissed

2024-12-31 06:39 UTC, rrojan approved these changes
LGTM :trophy:

2024-12-31 07:03 UTC, saugatmaharjan commented on src/config/env.config.ts
> +const validationSchema = z
`validationSchema`-> `appEnvSchema`

2024-12-31 07:04 UTC, saugatmaharjan commented on .gitignore
> +ormconfig.json
should this file be ignored @pratham-outside

2025-01-02 04:59 UTC, saugatmaharjan approved these changes

2025-01-02 05:15 UTC, noxiousghost approved these changes

2025-01-02 05:21 UTC, merged